name: rescue_station
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: 4.6.6
  #间距组件
  gap: ^3.0.1
  #网络请求
  dio: ^4.0.6
  #文字滚动组件
  marquee: ^2.2.3
  #视口组件
  flutter_screenutil: ^5.5.4
  #轮播图组件
  flutter_swiper_view: ^1.1.8
  #滑动条组件
  flutter_slidable: ^3.1.0
  #上下滑动刷新以及分页
  easy_refresh: ^3.4.0
  #网格布局组件
  flutter_staggered_grid_view: ^0.6.2
  #本地存储组件
  shared_preferences: 2.2.3
  #Icon组件
  cupertino_icons: ^1.0.6
  #工具组件
  common_utils: ^2.1.0
  #跨域代理组建
  shelf_proxy: ^1.0.1
  #加载动画
  flutter_easyloading: ^3.0.5
  #聊天组件
  flutter_chat_ui: ^1.6.14
  flutter_chat_types: ^3.6.2
  bubble: ^1.2.1
  #组件扩展
  getwidget: ^4.0.0
  #头像
  image_picker: ^1.1.2
  #日期
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  #文件选择
  file_picker: 8.0.6
  #表情包
  emoji_picker_flutter: ^2.2.0
#  google_fonts: ^6.2.1
  flutter_keyboard_visibility: ^6.0.0
  #socket通信
  web_socket_channel: ^3.0.1
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  #数据库
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: 0.4.3+2
  cached_network_image: ^3.3.1
  just_audio: ^0.9.39
  lifecycle: ^0.8.0
  scrollable_positioned_list: ^0.3.8
  lpinyin: ^2.0.3
  custom_pop_up_menu: ^1.2.4
  google_fonts: ^6.2.1
  #相机权限
  permission_handler: ^10.2.0

dependency_overrides:
  meta: ^1.10.0 # 替换为你需要的meta库的版本号
  vm_service: 14.2.1
  intl: 0.19.0
  web: 1.0.0
  json_serializable: ^6.6.2
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  #数据库自动编译
#  hive_generator: 2.0.1
  build_runner: 2.4.11



flutter:
  uses-material-design: true
  assets:
    - assets/images/banner/
    - assets/images/icon/
    - assets/music/
    - assets/fonts/
  fonts:
    - family: rescue
      fonts:
        - asset: assets/fonts/iconfont.ttf
#    - family: NotoColorEmoji
#      fonts:
#        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
flutter_intl:
  enabled: true

